apiVersion: v1
kind: Service
metadata:
  name: tb-node
  namespace: thingsboard
spec:
  # type: ClusterIP
  type: NodePort
  selector:
    app: tb-node
  ports:
  - port: 8080
    name: http
    nodePort: $selected_port
