apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tb-node
  namespace: thingsboard
spec:
  serviceName: tb-node
  replicas: 1
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: tb-node
  template:
    metadata:
      labels:
        app: tb-node
    spec:
      volumes:
        - name: tb-node-config
          configMap:
            name: tb-node-config
            items:
            - key: conf
              path:  thingsboard.conf
            - key: logback
              path:  logback.xml
        - name: tb-node-logs
          emptyDir: {}
      containers:
      - name: server
        imagePullPolicy: IfNotPresent
        image: thingsboard/tb-node:3.2.0
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: rpc
        env:
        - name: TB_SERVICE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TB_SERVICE_TYPE
          value: "monolith"
        - name: TB_QUEUE_TYPE
          value: "kafka"
        - name: ZOOKEEPER_ENABLED
          value: "true"
        - name: ZOOKEEPER_URL
          value: "zookeeper:2181"
        - name: TB_KAFKA_SERVERS
          value: "tb-kafka:9092"
        - name: JS_EVALUATOR
          value: "remote"
        - name: TRANSPORT_TYPE
          value: "remote"
        - name: HTTP_LOG_CONTROLLER_ERROR_STACK_TRACE
          value: "false"
        envFrom:
        - configMapRef:
            name: tb-node-db-config
        - configMapRef:
            name: tb-node-cache-config
        volumeMounts:
          - mountPath: /config
            name: tb-node-config
          - mountPath: /var/log/thingsboard
            name: tb-node-logs
        readinessProbe:
          httpGet:
            path: /login
            port: http
        livenessProbe:
          httpGet:
            path: /login
            port: http
          initialDelaySeconds: 360
          timeoutSeconds: 10
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: $selected_node_resources

