apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datalog-zookeeper-0
  namespace: thingsboard
  labels:
    app: zookeeper
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
