kind: PersistentVolume
apiVersion: v1
metadata:
  name: tb-coap-transport-logs-0
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 200Mi
  local:
    path: /mnt/tb-coap-transport-logs-0
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  claimRef:
     namespace: thingsboard
     name: logs-tb-coap-transport-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - $selected_node_resources
