apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-tb-coap-transport-0
  namespace: thingsboard
  labels:
    app: tb-coap-transport
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
