apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-tb-mqtt-transport-1
  namespace: thingsboard
  labels:
    app: tb-mqtt-transport
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
