kind: PersistentVolume
apiVersion: v1
metadata:
  name: tb-mqtt-transport-logs-1
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 200Mi
  local:
    path: /mnt/tb-mqtt-transport-logs-1        #This path should be created manually on node
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  claimRef:
     namespace: thingsboard
     name: logs-tb-mqtt-transport-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - $selected_node_resources
