kind: PersistentVolume
apiVersion: v1
metadata:
  name: cassandra-data
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Gi
  local:
    path: /mnt/cassandra-data        #This path should be created manually on node
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  claimRef:
     namespace: thingsboard
     name: cassandra-data-cassandra-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - $selected_node
