apiVersion: v1
kind: Service
metadata:
  name: tb-kafka
  namespace: thingsboard
spec:
  type: NodePort
  selector:
    app: tb-kafka
  ports:
    - port: 9092
      name: kafka-int
      targetPort: 9092
    - port: 9093
      name: kafka-out
      targetPort: 9093
      nodePort: 30719

