apiVersion: v1
kind: Service
metadata:
  name: tb-redis
  namespace: thingsboard
spec:
  type: NodePort
  selector:
    app: tb-redis
  ports:
    - name: tb-redis-port
      port: 6379
      targetPort: 6379
      nodePort: 31112
